
name: "Bug Report"
description: Suggest an idea for this project.
labels: ["enhancement"]
fields:
- type: "textarea"
  attributes:
    label: "Is your feature request related to a problem?"
    description: "If so, describe what the problem is"
    placeholder: "eg. I'm always frustrated when [...]"
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Describe the solution you'd like"
    description: "Describe what you want to happen"
    placeholder: "eg. The bot should do [...] then [...]"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "What alternatives have you considered?"
    description: "Feel free to mention other Discord bots if you feel this will get your point across better"
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Additional context"
    description: "Add any other context or screenshots about the feature request here"
  validations:
    required: false