// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.DefaultPrefix(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.MessageCreateEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.HandleCommandAlias(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.MessageCreateEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Services.Localization.AkkoLocalizer.GetResponseString(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.VoiceRole(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.VoiceStateUpdateEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.SaveGuildOnJoin(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.GuildCreateEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.PollVote(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.MessageCreateEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.FilterSticker(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.MessageCreateEventArgs)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.FilterWord(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.MessageCreateEventArgs)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Extensions.DiscordChannelExt.GetMessagesAsync(DSharpPlus.Entities.DiscordChannel,DSharpPlus.DiscordClient,System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{DSharpPlus.Entities.DiscordMessage}}")]
[assembly: SuppressMessage("Style", "IDE0053:Use expression body for lambda expressions", Justification = "Lambda would impair readability.", Scope = "member", Target = "~F:AkkoBot.Commands.Formatters.AkkoPlaceholders._parameterizedActions")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.SanitizeNameOnJoinAsync(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.GuildMemberAddEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Ternary would impair readability.", Scope = "member", Target = "~M:AkkoBot.Core.Services.GlobalEvents.SanitizeNameOnUpdateAsync(DSharpPlus.DiscordClient,DSharpPlus.EventArgs.GuildMemberUpdateEventArgs)~System.Threading.Tasks.Task")]